const routes = {
  home: "HOME",
  login: "LOGIN",
  profile: "PROFILE",
  updatekyc: "UPDATE KYC",
  user_profile: 'USER PROFILE',
  user_requests:'USER REQUESTS',
  users:'USERS',
  news: "NEWS",
  single_news: "SINGLE NEWS",
  complaint: "COMPLAINT",
  meeting: "MEETING",
  location: "LOCATION",
  user_complaints: "USER COMPLAINTS",
  user_meetings: "USER MEETINGS",
  user_news: "USER NEWS",
  slots: "UPDATE SLOTS",
  single_meeting: "SINGLE MEETING",
  single_complaint: "SINGLE COMPLAINT",
  create_meeting: "BOOK MEETING",
  create_news: "CREATE NEWS",
  requests: "REQUESTS & USERS",
  create_complaint: "CREATE COMPLAINT",
  update_meeting: "UPDATE MEETING",
};

export default routes;
