const routes = {
  home: "Home",
  login: "Login",
  profile: "Profile",
  mainscreen: "Main Screen",
  about: "About",
  navarathnalu: "Navarathnalu",
  posts: "Posts",
  notifications: "Notifications",
  referfriend: "Refer a Friend",
  gallary: "Gallary",
  contact: "Contact Us",
  updatekyc: "Update Kyc",
  user_profile: 'User Profile',
  user_requests:'User Requests',
  users:'Users',
  news: "News",
  single_news: "Single News",
  complaint: "Complaint",
  meeting: "Meeting",
  location: "Location",
  user_complaints: "User Complaints",
  user_meetings: "User Meetings",
  user_news: "User News",
  slots: "Update Slots",
  single_meeting: "Single Meeting",
  single_complaint: "Single Complaint",
  create_meeting: "Book Meeting",
  create_news: "Create News",
  requests: "Requests & Users",
  admin:"Designated & Admin",
  create_complaint: "Create Complaint",
  update_meeting: "Update Meeting",
};

export default routes;
